# Generated by Django 4.2 on 2023-05-02 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textToSpeech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 15, 29, 50, 861838)),
        ),
    ]
