# Generated by Django 4.2 on 2023-05-03 09:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textToSpeech', '0003_alter_pdf_upload_on_epub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epub',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 14, 50, 50, 1712)),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='path',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 14, 50, 50, 707)),
        ),
        migrations.CreateModel(
            name='HTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('path', models.CharField(blank=True, max_length=100)),
                ('text', models.CharField(blank=True, max_length=1000)),
                ('status', models.BooleanField(default=False)),
                ('upload_on', models.DateTimeField(default=datetime.datetime(2023, 5, 3, 14, 50, 50, 2712))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
