# Generated by Django 4.2 on 2023-05-10 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textToSpeech', '0008_alter_epub_upload_on_alter_html_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='html',
            old_name='status',
            new_name='summary_status',
        ),
        migrations.AddField(
            model_name='html',
            name='text_to_speech_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='epub',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 12, 30, 12, 961523)),
        ),
        migrations.AlterField(
            model_name='html',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 12, 30, 12, 963522)),
        ),
        migrations.AlterField(
            model_name='mp3',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 12, 30, 12, 964522)),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 12, 30, 12, 960521)),
        ),
        migrations.AlterField(
            model_name='summary',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 12, 30, 12, 965524)),
        ),
    ]
