# Generated by Django 4.2 on 2023-05-10 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textToSpeech', '0009_rename_status_html_summary_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='status',
        ),
        migrations.AlterField(
            model_name='epub',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='epub',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 18, 12, 5, 18462)),
        ),
        migrations.AlterField(
            model_name='html',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='html',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 18, 12, 5, 18462)),
        ),
        migrations.AlterField(
            model_name='mp3',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='mp3',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 18, 12, 5, 19461)),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 18, 12, 5, 17463)),
        ),
        migrations.AlterField(
            model_name='summary',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='summary',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 18, 12, 5, 20461)),
        ),
    ]
