# Generated by Django 4.2 on 2023-05-18 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textToSpeech', '0013_alter_epub_upload_on_alter_html_upload_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epub',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 16, 23, 10, 697160)),
        ),
        migrations.AlterField(
            model_name='html',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 16, 23, 10, 697160)),
        ),
        migrations.AlterField(
            model_name='mp3',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 16, 23, 10, 698161)),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 16, 23, 10, 696159)),
        ),
        migrations.AlterField(
            model_name='summary',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 16, 23, 10, 699162)),
        ),
    ]
