# Generated by Django 4.2.2 on 2023-06-30 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textToSpeech', '0016_alter_epub_upload_on_alter_html_upload_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='status',
            new_name='summary_status',
        ),
        migrations.AddField(
            model_name='text',
            name='parent_file',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='text_to_speech_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='epub',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 11, 58, 47, 823554)),
        ),
        migrations.AlterField(
            model_name='html',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 11, 58, 47, 823554)),
        ),
        migrations.AlterField(
            model_name='mp3',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 11, 58, 47, 823554)),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 11, 58, 47, 821553)),
        ),
        migrations.AlterField(
            model_name='summary',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 11, 58, 47, 824554)),
        ),
        migrations.AlterField(
            model_name='text',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 11, 58, 47, 822555)),
        ),
    ]
