# Generated by Django 4.2.2 on 2023-06-30 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textToSpeech', '0017_rename_status_text_summary_status_text_parent_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='total_charachter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='epub',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 16, 4, 41, 267588)),
        ),
        migrations.AlterField(
            model_name='html',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 16, 4, 41, 268588)),
        ),
        migrations.AlterField(
            model_name='mp3',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 16, 4, 41, 268588)),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 16, 4, 41, 266589)),
        ),
        migrations.AlterField(
            model_name='summary',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 16, 4, 41, 269601)),
        ),
        migrations.AlterField(
            model_name='text',
            name='upload_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 16, 4, 41, 267588)),
        ),
    ]
