# Generated by Django 4.2 on 2023-05-02 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 15, 29, 50, 863838), editable=False),
        ),
    ]
