# Generated by Django 4.2 on 2023-05-10 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_passwordreset_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 12, 30, 12, 968518), editable=False),
        ),
    ]
