# Generated by Django 4.2 on 2023-06-13 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_passwordreset_expires_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 16, 53, 0, 687896), editable=False),
        ),
    ]
