# Generated by Django 4.2.2 on 2023-06-27 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_passwordreset_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 15, 31, 20, 829026), editable=False),
        ),
    ]
